name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "![](https://cdn.anishdoes.dev/githublight.png)\nHey @{user}! Welcome to the **QBOT** repo on **Github**."
        pr-message: "Message that will be displayed on users' first pull request"
  
  auto-lgtm:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: lazy-actions/lgtm-image-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          favorite-image: 'https://your.favorite/image1.png,https://your.favorite/image2.png'
